### PR TITLE
Issue #21: Refactor for testing

### PR DESCRIPTION
**Pull request by btruhand**
Hi I've made the PR for the issue. There are two things I want to note:

- My development setting is 2 spaces instead of 4 spaces. In case you want me to change it just tell me
- Not related to my changes I think but when you try to stache tabs that only consists of ignored tabs or blank tabs when you try to unload the stache, the stache list won't be updated. It seems to exist in the current version too. Though it is kind of useless to stache such tabs, so probably not much of an issue

### CODE REVIEW

**Comment by btruhand** [comment]
@dngrhm forgot to set the reviewer so feel free to add yourself

**Comment by dngrhm** [comment]
Awesome! @btruhand Initial peek looks good.  I'll look into it a little more deeply when I get a chance.  I prefer 2 spaces, so you're good there! 👍 Thanks for the PR submission and good luck with the rest of Hacktoberfest

**Comment by btruhand** [comment]
@dngrhm alright 👍 tell me if you have any concerns

**Comment by dngrhm** [comment]
@btruhand Thanks for the PR.  Good luck in your Hacktoberfesting!!

**Pull request merged**
